### ISSUE TITLE
Received savefile validation

### ISSUE THREAD

**Issue by k-cybulski** [civ5-pbem/civ5-pbem-server#25]
The server should have two modes for accepting uploaded files:
 
- With validation, where prior to accepting new saves it should check:
  - Is current player (who should move next) the next player after the uploader
  - If the uploader was the last human player in a turn, the turn number should go up by 1
- Without validation, for periods of local hot seat, where it should not check either of the requirements. 
  - After a save had been uploaded the game should return to validation mode
  - Maybe the host should select who can upload the file/confirm who performed the last turn?

The host should be able to switch between the modes during play. Other players should be informed of that fact - by email, server messages when attempting to download/upload saves or any other means.

**Comment by mcybulsk** [comment]
Maybe file size should also be validated to counter the famous save-game bloating.

**Comment by mcybulsk** [comment]
Opened #27 for the anti-file-bloating validation.

**Comment by mcybulsk** [comment]
Pull request #26 is waiting for review.
